### ISSUE TITLE
Latest pull yields nothing

### ISSUE THREAD

**Issue by mattTrueEx** [mdnpascual/Padherder_Extender#2]
found this error with the latest pull.   firefox 58.0.1 64 bit

This library requires Greasemonkey! GM_setValue is missing.
Padherder:667:13
This library requires Greasemonkey! GM_getValue is missing.
Padherder:667:13
Script error:  
ReferenceError: GM_getValue is not defined
Stack trace:
userScript/<@user-script:PadherderExtender/Padherder:409:442
userScript@user-script:PadherderExtender/Padherder:379:2
scopeWrapper@user-script:PadherderExtender/Padherder:11188:9
@user-script:PadherderExtender/Padherder:361:17

**Comment by mdnpascual** [comment]
Ye, just tested at  firefox and it does show that error

**Comment by mdnpascual** [comment]
Removed GM_set and get value for now. This should work now but going to test how it behaves a few minutes after each day

**Comment by mdnpascual** [comment]
The DB Account for padherder currently got flagged sooooooo nvm that, this is going to be down until that is resolved
